### PR TITLE
add basic test

### PR DESCRIPTION
**Pull request by madhur-tandon**

### CODE REVIEW

**Comment by madhur-tandon** [comment]
@SylvainCorlay This PR works for `Mac` and `Ubuntu` but fails for `Windows`.

The failure on `Windows` happens first which leads to cancelling the scheduled jobs for `Mac` and `Ubuntu`.

I am not sure why it fails but here is the message from the logs:

```
D:\a\xvega\xvega\test\test_basic_chart.cpp(8,83): error C3849: function-style call on an expression of type 'xp::xproperty<xtl::xoptional<std::string,bool>,xv::url_data>' would lose const and/or volatile qualifiers for all 5 available operator overloads [D:\a\xvega\build\test\test_xvega_lib.vcxproj]
D:\a\xvega\xvega\test\test_basic_chart.cpp(10,31): error C3536: 'df': cannot be used before it is initialized [D:\a\xvega\build\test\test_xvega_lib.vcxproj]
D:\a\xvega\xvega\test\test_basic_chart.cpp(10,31): error C3849: function-style call on an expression of type 'xp::xproperty<xv::data_type,xv::Chart>' would lose const and/or volatile qualifiers for all 5 available operator overloads [D:\a\xvega\build\test\test_xvega_lib.vcxproj]
D:\a\xvega\xvega\test\test_basic_chart.cpp(11,43): error C3536: 'fig': cannot be used before it is initialized [D:\a\xvega\build\test\test_xvega_lib.vcxproj]
D:\a\xvega\xvega\test\test_basic_chart.cpp(11,43): error C2665: 'xv::mime_bundle_repr': none of the 4 overloads could convert all the argument types [D:\a\xvega\build\test\test_xvega_lib.vcxproj]

D:\a\xvega\xvega\include\xvega/xvega.hpp(27,21): message : could be 'nlohmann::json xv::mime_bundle_repr(const xv::Chart &)' [D:\a\xvega\build\test\test_xvega_lib.vcxproj]
D:\a\xvega\xvega\include\xvega\grammar/view_compositions/vconcat.hpp(25,21): message : or       'nlohmann::json xv::mime_bundle_repr(const xv::vconcat &)' [D:\a\xvega\build\test\test_xvega_lib.vcxproj]
D:\a\xvega\xvega\include\xvega\grammar/view_compositions/hconcat.hpp(25,21): message : or       'nlohmann::json xv::mime_bundle_repr(const xv::hconcat &)' [D:\a\xvega\build\test\test_xvega_lib.vcxproj]
D:\a\xvega\xvega\include\xvega\grammar/view_compositions/layering.hpp(25,21): message : or       'nlohmann::json xv::mime_bundle_repr(const xv::layer &)' [D:\a\xvega\build\test\test_xvega_lib.vcxproj]
```

If I remove `windows` as one of the machines, this PR would have passed on `Mac` and `Ubuntu`.

**Comment by madhur-tandon** [comment]
@SylvainCorlay I know. I already rebased and force pushed. This seems to occur even after doing so.

**Comment by SylvainCorlay** [comment]
ok, looking into it.

**Comment by SylvainCorlay** [comment]
As discussed in person, let's get this in and fix the windows build in another iteration.

**Pull request merged**
