### PR TITLE
Export symbols on windows

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@madhur-tandon this is ready to go.
This will be necessary to link the tests with xvega on windows.

**Comment by madhur-tandon** [comment]
I see, I removed `windows` as a machine from the other PR (https://github.com/QuantStack/xvega/pull/22) since it was failing there. And a failure on `windows` lead to cancelling of the jobs on `Mac` and `Ubuntu` as well due to which I couldn't see the status there. Would merging this solve that?

**Comment by SylvainCorlay** [comment]
Maybe, you would need to rebase your PR on master after merging.

**Comment by madhur-tandon** [comment]
Cool, let's do it.

**Pull request merged**
