### PR TITLE
add suggested RPATH settings

### PR DESCRIPTION
**Pull request by madhur-tandon**
@JohanMabille I have implemented the suggested changes. I am able to build it locally. It works like it used to work before this change. The size is also same (702 KB) when built locally.

How can I verify if this if it will work when I install it from `conda-forge` as well? Will I have to release a new dummy version to check this?

PS -- Do these changes look fine or do you suggest something else?

I found something related done by Xeus here: https://github.com/jupyter-xeus/xeus/blob/2ab819a0953793c7d743f1479be230dca9a39fd9/CMakeLists.txt#L194 and https://github.com/jupyter-xeus/xeus/blob/2ab819a0953793c7d743f1479be230dca9a39fd9/CMakeLists.txt#L222

^^Do I copy these 2 snippets perhaps?

### CODE REVIEW

**Comment by JohanMabille** [comment]
You can extract a patch from your diff and add it to the recipe. Then build the recipe and install it. You can iterate faster if you do it locally rather than on conda-forge.

**Comment by madhur-tandon** [comment]
I have merged the 2 snippets from the links posted in the above comment into a single snippet.
Let me know if this is good to go.

I am still not sure about
`set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib; ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}”)`
here: https://github.com/jupyter-xeus/xeus/blob/2ab819a0953793c7d743f1479be230dca9a39fd9/CMakeLists.txt#L199

^^This is present just below the first snippet in `Xeus`

**Comment by JohanMabille** [comment]
LGTM.

The reason for `set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib; ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}”)` is that on some system `CMAKE_INSTALL_LIBDIR` is not `lib` (it can be `lib64` for instance). So, if you don't explicitly set it to `lib` when invoking `CMake`, the previous line ensures it will be in the RPATH.

**Comment by madhur-tandon** [comment]
Thanks, So we need

`set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib; ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}”)`

or not?

This PR didn't include it.
I can send a separate PR if it's needed.

From your comment, it seemed like we should have included it.

**Comment by JohanMabille** [comment]
Yep you can add it in a dedicated PR.

**Pull request merged**
